export const getNodeDocumentation = (label: string): string => {
  const docs: Record<string, string> = {
    'File Watcher': 'Instructs the engine to monitor folder systems or local storage. Fires whenever a changes event is registered.',
    'Cloud Event': 'Listens for telemetry, infrastructure, or platform trigger Webhook payload bundles.',
    'Webhook In': 'Exposes an endpoint that accepts external POST/GET payloads to start the flow.',
    'CADD Update': 'Polls or receives notifications of CAD/drawing modification files. Synthesizes geometry.',
    'Form Entry': 'Triggered on submission of digital intake, specification lists, or approval documents.',
    'Cron Timer': 'Trims state and fires execution nodes periodically on an engineered interval schedule.',
    'Slack Notify': 'Pipes messages, diagnostics, and structured summaries directly into registered Slack workspace channels.',
    'Discord Push': 'Broadcasts alerts and event logs to a designated Discord webhook portal.',
    'Teams Bridge': 'Coordinates enterprise department bulletins within Microsoft Teams rooms.',
    'Email SMTP': 'Sends transactional logs, system summaries, or client estimates through institutional mail ports.',
    'WhatsApp API': 'Broadcasts instant customer or engineer SMS alerts through the WhatsApp Business portal.',
    'CAD Archive': 'Compresses structural models, metadata logs, and dwg configurations into verified archives.',
    'Layer Map': 'Extracts visual elements, alignments, and drawing layers for structural parsing.',
    'Plot Check': 'Audits drawing scale ratios, line weight compliance, and spatial bounds before release.',
    'Revise Sync': 'Publishes version delta packets across collaborative client platforms.',
    'Sub-Workflow': 'Nests an entirely separate logical pipeline template within the current executive flow.',
    'Human Approval': 'Pauses execution until an authorized admin reviews diagnostics and clicks Approve.',
    'Logic Gate': 'Evaluates parameters against algebraic constraints to decide on conditional execution paths.',
    'Figma Hook': 'Subscribes to file edit signals to trigger design-to-production logic pipelines.',
    'VoxCadd Sync': 'Syncs spatial vectors, materials, and parts directly into the 3D web viewport.',
    'Rhino Link': 'Sends design configurations to McNeel Rhino automation instances in headless server blocks.',
    'SolidWorks Ops': 'Triggers heavy sheet metal modeling, CAD pipelines, or material calculations on worker nodes.',
    'AI Trigger': 'Monitors incoming feeds with language filters, firing when prompt objectives are met.',
    'Figma Parser': 'Uses AI vision to parse and decompose Figma layer drawings into CAD instructions.',
    'CAD Archival': 'Smart indexes 2D floor plans and 3D schematics into automated knowledge bases.',
    'Filter Data': 'Applies strict logic predicates to strip out garbage telemetry and unwanted entries.',
    'JSON Map': 'Reshapes complex nesting payloads into clean objects using structured mappings.',
    'Delay (5s)': 'Holds execution context for a 5 second period before clearing downstream channels.',
    'Security Gate': 'Ensures cryptographic keys, role access tokens, and payload formats are valid.',
    'Process Data': 'Extracts database tables, formats entries, and runs custom analytics processes.',
    'AI Classify': 'Applies semantic classifiers to filter customer emails or bug tickets into key channels.',
    'Auto Summarize': 'Condenses long documents, change requests, or logs into short action bulletins.',
    'Vector Index': 'Upserts analytical indices into localized Vector DB instances for fast semantic lookups.',
    'Agent Hub': 'Spawns specialized LLM crew interactions to research issues and coordinate operations.',
    'Archive Agent': 'Executes deep, autonomous structural searches and retention tasks.',
    'Coord Agent': 'Coordinates timelines, tasks, and machine availability cycles autonomously.',
    'CAD Agent': 'Synthesizes draft variations based on generative design constraints.',
    'Guardian': 'Stands vigil over server memory, budget quotas, and sensitive PII exposures.'
  };
  return docs[label] || 'Executes custom automated rules and pipes parameters down the neural logic mesh.';
};
